version: '3.9'
services:

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    #restart: unless-stopped
    #tty: true
    ports:
      - '80:80'
      #- "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
#Docker Networks
networks:
  mynet:
    driver: bridge

